import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'tailwindcss/tailwind.css';
import './globals.css';
import NavigationComponent from '@/components/navigation/navigation';

// font
const inter = Inter({ subsets: ['latin'] });
// meta
export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: layoutType) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden `}>
        <NavigationComponent />
        <div className="wave" style={{ width: 500, height: 500 }}></div>
        <div className="wave" style={{ width: 700, height: 700 }}></div>
        <div className="wave" style={{ width: 1000, height: 1000 }}></div>

        {children}
      </body>
    </html>
  );
}
