import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'tailwindcss/tailwind.css';
import './globals.css';
import NavigationComponent from '@/components/navigation/navigation';
import Wave from '@/components/wave/wave';

// font
const inter = Inter({ subsets: ['latin'] });
// meta
export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: layoutType) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden `}>
        <NavigationComponent />
        <Wave />
        {children}
      </body>
    </html>
  );
}
